import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`; not ours to lint.
    "src/generated/**",
    // Vendored third-party tool, pinned to an upstream release tag.
    "vendor/**",
  ]),
  {
    // Test files are scaffolds: they import the surface under test and
    // leave the assertions as TODOs for the author to write by hand. The
    // unused-import warnings that produces are expected, and silencing
    // them here beats littering the scaffolds with `void x;` statements.
    files: ["tests/**/*.ts", "tests/**/*.tsx"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
]);

export default eslintConfig;
